db = connect( 'mongodb://localhost:27017/VOD-dashboard' );
db.createCollection('Admin')
db.Admin.insert({'username':'admin','password':'f6fdffe48c908deb0f4c3bd36c032e72','title':'narges salehi','email':'admin@admin.com','avatar_id':'test',
'status':'Active','last_access_time':ISODate('2022-09-04 17:25:45.768+00:00'),'access_group_ids':[],'super_admin':true})
db.createCollection('Provider')
db.Provider.insert({'name':'namava','dc_id':'','logo_file_id':'','url':'/example'})
db.createCollection('Access')
db.Access.insert({'access':'AddProvider'})
db.createCollection('AccessGroup')
db.AccessGroup.insert({'title':'one','accesses':[]})
db.createCollection('DataCenterInfo')
db.DataCenterInfo.insert({'download_url':'/example','upload_url':'/example'})
db.createCollection('File')
db.File.insert({'dc_id':'','status':'Done','type':'Avatar','download_url':'/example'})
db.createCollection('Tag')
db.Tag.insert({'name':'shit'})
db.createCollection('Genre')
db.Genre.insert({'name':'shit'})
db.createCollection('Person')
db.Person.insert({'name':'shit','role':'Director'})
db.Person.insert({'name':'shit','role':'Actor'})
db.Person.insert({'name':'shit','role':'Actress'})
db.Person.insert({'name':'shit','role':'Producer'})
db.createCollection('ContentAccessLog')
db.ContentAccessLog.insert({'content_id':'','provider_id':'','date_hourly':'','isp_name':'MTN','accessed_bytes':22342,'traffic_factor':1})
db.createCollection('TotalTraffic')
db.TotalTraffic.insert({'date_hourly':'','isp_name':'MTN','accessed_bytes':22342,'traffic_factor':1})
db.createCollection('ContentSegmentCount')
db.ContentSegmentCount.insert({'content_id':'','segment':'','quality':420,'access_count':1000})
